language: go

jobs:
  include:
  - os: linux # default
    arch: amd64
    go: master
  - os: linux
    arch: arm64 # arch
    go: master
  - os: linux
    arch: ppc64le # arch
    go: master
  - os: linux
    arch: s390x # arch
    go: master
  - os: linux
    arch: amd64
    go: 1.13.x # go version
  - os: osx # os
    arch: amd64
    go: master
  - os: windows # os
    arch: amd64
    go: 1.13.x
  allow_failures:
  - os: windows # sometimes fail in TravisCI with unknown reason
    arch: amd64
    go: 1.13.x

script:
  - ./build.sh && ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
